# Generated by Django 4.2.29 on 2026-04-17 00:04

from django.db import migrations, models

import posthog.models.feature_flag.feature_flag


class Migration(migrations.Migration):
    dependencies = [
        ("posthog", "1104_alter_organization_is_ai_data_processing_approved")
    ]

    operations = [
        migrations.AlterField(
            model_name="featureflag",
            name="filters",
            field=models.JSONField(
                default=posthog.models.feature_flag.feature_flag.default_filters
            ),
        ),
        # Idempotent backfill enforcing the groups-key invariant on existing rows.
        migrations.RunSQL(
            sql="""
                UPDATE posthog_featureflag
                SET filters = COALESCE(filters, '{}'::jsonb) || '{"groups": []}'::jsonb
                WHERE filters IS NULL
                   OR NOT (filters ? 'groups');
            """,
            reverse_sql=migrations.RunSQL.noop,
            elidable=True,
        ),
    ]
