# Generated by Django 4.2.29 on 2026-04-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posthog", "1109_alert_investigation_notification_gating"),
    ]

    operations = [
        migrations.AddField(
            model_name="integration",
            name="repository_cache",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="integration",
            name="repository_cache_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
